#!/usr/bin/env python
#
# Software License Agreement (BSD License)
#
# Copyright (c) 2010, Antons Rebguns. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the name of University of Arizona nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Data output scale factors
SCALE_YAW = 0.0109863           # degrees/LSB
SCALE_PITCH = 0.0109863
SCALE_ROLL = 0.0109863
SCALE_YAW_RATE = 0.0137329      # degrees/second/LSB
SCALE_PITCH_RATE = 0.0137329
SCALE_ROLL_RATE = 0.0137329
SCALE_MAG_X = 0.061035          # mGauss/LSB
SCALE_MAG_Y = 0.061035
SCALE_MAG_Z = 0.061035
SCALE_GYRO_X = 0.01812          # degrees/second/LSB
SCALE_GYRO_Y = 0.01812
SCALE_GYRO_Z = 0.01812
SCALE_ACCEL_X = 0.106812        # mg/LSB
SCALE_ACCEL_Y = 0.106812
SCALE_ACCEL_Z = 0.106812

# RX packets
SET_FIR_CORNERS = 0x80
SET_FIR_TAPS = 0x81
SET_ACTIVE_CHANNELS = 0x82
SET_SILENT_MODE = 0x83
SET_BROADCAST_MODE = 0x84
SET_X_GYRO_BIAS = 0x85
SET_Y_GYRO_BIAS = 0x86
SET_Z_GYRO_BIAS = 0x87
SET_X_ACCEL_BIAS = 0x88
SET_Y_ACCEL_BIAS = 0x89
SET_Z_ACCEL_BIAS = 0x8a
ZERO_RATE_GYROS = 0x8b
SELF_TEST = 0x8c
SET_PROCESS_WEIGHT = 0x8c
SET_PROCESS_WEIGHT = 0x8D
WRITE_TO_FLASH = 0xa0
GET_DATA = 0x01
GET_GYRO_BIAS = 0x02
GET_ACCEL_BIAS = 0x03
GET_FIR_CONFIG = 0x04
GET_FIR_TAP_CONFIG = 0x05
GET_ACTIVE_CHANNELS = 0x06
GET_BROADCAST_MODE = 0x07
GET_PROCESS_WEIGHT = 0x08


# TX packets
COMMAND_COMPLETE = 0xB0
COMMAND_FAILED = 0xB1
BAD_CHECKSUM = 0xB2
BAD_DATA_LENGTH = 0xB3
UNRECOGNIZED_PACKET = 0xB4
BUFFER_OVERFLOW = 0xB5
STATUS_REPORT = 0xB6
SENSOR_DATA = 0xB7
GYRO_BIAS_REPORT = 0xB8
GYRO_SCALE_REPORT = 0xB9
START_CAL_REPORT = 0xBA
ACCEL_BIAS_REPORT = 0xBB
FIR_CONFIG_REPORT = 0xBB
ACTIVE_CHANNEL_REPORT = 0xBC
BROADCAST_MODE_REPORT = 0xBD
PROCESS_WEIGHT_REPORT = 0xBE

CODE_TO_STR = {
    SET_ACTIVE_CHANNELS: "SET_ACTIVE_CHANNELS",
    SET_SILENT_MODE: "SET_SILENT_MODE",
    SET_BROADCAST_MODE: "SET_BROADCAST_MODE",
    ZERO_RATE_GYROS: "ZERO_RATE_GYROS",
    SELF_TEST: "SELF_TEST",
    WRITE_TO_FLASH: "WRITE_TO_FLASH",
    
    GET_DATA: "GET_DATA",
    GET_ACTIVE_CHANNELS: "GET_ACTIVE_CHANNELS",
    GET_BROADCAST_MODE: "GET_BROADCAST_MODE",
    GET_ACCEL_BIAS: "GET_ACCEL_BIAS",
    GET_GYRO_BIAS: "GET_GYRO_BIAS",
    
    
    COMMAND_COMPLETE: "COMMAND_COMPLETE",
    COMMAND_FAILED: "COMMAND_FAILED",
    BAD_CHECKSUM: "BAD_CHECKSUM",
    BAD_DATA_LENGTH: "BAD_DATA_LENGTH",
    UNRECOGNIZED_PACKET: "UNRECOGNIZED_PACKET",
    BUFFER_OVERFLOW: "BUFFER_OVERFLOW",
    STATUS_REPORT: "STATUS_REPORT",
    SENSOR_DATA: "SENSOR_DATA",
    GYRO_BIAS_REPORT: "GYRO_BIAS_REPORT",
    GYRO_SCALE_REPORT: "GYRO_SCALE_REPORT",
    START_CAL_REPORT: "START_CAL_REPORT",
    ACCEL_BIAS_REPORT: "ACCEL_BIAS_REPORT",
    ACTIVE_CHANNEL_REPORT: "ACTIVE_CHANNEL_REPORT",
    BROADCAST_MODE_REPORT: "BROADCAST_MODE_REPORT",
}
