"""autogenerated by genpy from sdc2130_skel/odom_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class odom_msg(genpy.Message):
  _md5sum = "abb86dc7f287993ac5af62321d84ad5f"
  _type = "sdc2130_skel/odom_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 rotX
int64 rotY
float64 distX
float64 distY

"""
  __slots__ = ['rotX','rotY','distX','distY']
  _slot_types = ['int64','int64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rotX,rotY,distX,distY

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(odom_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.rotX is None:
        self.rotX = 0
      if self.rotY is None:
        self.rotY = 0
      if self.distX is None:
        self.distX = 0.
      if self.distY is None:
        self.distY = 0.
    else:
      self.rotX = 0
      self.rotY = 0
      self.distX = 0.
      self.distY = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2q2d.pack(_x.rotX, _x.rotY, _x.distX, _x.distY))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.rotX, _x.rotY, _x.distX, _x.distY,) = _struct_2q2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2q2d.pack(_x.rotX, _x.rotY, _x.distX, _x.distY))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.rotX, _x.rotY, _x.distX, _x.distY,) = _struct_2q2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2q2d = struct.Struct("<2q2d")
