/* Auto-generated by genmsg_cpp for file /home/skel/roboskel_workspace/sandbox/servo_mast/msg/mast_turn.msg */
#ifndef SERVO_MAST_MESSAGE_MAST_TURN_H
#define SERVO_MAST_MESSAGE_MAST_TURN_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace servo_mast
{
template <class ContainerAllocator>
struct mast_turn_ {
  typedef mast_turn_<ContainerAllocator> Type;

  mast_turn_()
  : header()
  , position(0.0)
  , acceleration(0.0)
  , velocity(0.0)
  {
  }

  mast_turn_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , position(0.0)
  , acceleration(0.0)
  , velocity(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _position_type;
  double position;

  typedef double _acceleration_type;
  double acceleration;

  typedef double _velocity_type;
  double velocity;


  typedef boost::shared_ptr< ::servo_mast::mast_turn_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_mast::mast_turn_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct mast_turn
typedef  ::servo_mast::mast_turn_<std::allocator<void> > mast_turn;

typedef boost::shared_ptr< ::servo_mast::mast_turn> mast_turnPtr;
typedef boost::shared_ptr< ::servo_mast::mast_turn const> mast_turnConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::servo_mast::mast_turn_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::servo_mast::mast_turn_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace servo_mast

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::servo_mast::mast_turn_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::servo_mast::mast_turn_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::servo_mast::mast_turn_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ea34dd6630c54e8f4488f724a724b9c0";
  }

  static const char* value(const  ::servo_mast::mast_turn_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xea34dd6630c54e8fULL;
  static const uint64_t static_value2 = 0x4488f724a724b9c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_mast::mast_turn_<ContainerAllocator> > {
  static const char* value() 
  {
    return "servo_mast/mast_turn";
  }

  static const char* value(const  ::servo_mast::mast_turn_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::servo_mast::mast_turn_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 position\n\
float64 acceleration\n\
float64 velocity\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::servo_mast::mast_turn_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::servo_mast::mast_turn_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::servo_mast::mast_turn_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::servo_mast::mast_turn_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.position);
    stream.next(m.acceleration);
    stream.next(m.velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct mast_turn_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_mast::mast_turn_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::servo_mast::mast_turn_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.acceleration);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SERVO_MAST_MESSAGE_MAST_TURN_H

